### ISSUE TITLE
Simulated Data Set Availability?

### ISSUE THREAD

**Issue by ryanbthomas** [wueth/Experience-Rating-in-Insurance-Pricing#1]
Thank you for making the draft lecture notes available. I'm planning on working through the lecture notes and some of the related papers with some colleagues to further our understanding of the topics.

Would it be possible to add information on how the simulated was created and/or a copy of the simulated dataset to this repo?

**Comment by wueth** [comment]
Dear Ryan: Thanks for your interests and your request! I have just uploaded the synthetic data that has been used in the lecture notes. I will also make available the code to replicate the examples, however, polishing the code requires some more work. Thanks for your patience!

**Comment by ryanbthomas** [comment]
I can appreciate that prepping the code requires more time/effort. Thank you!
